name: Trigger auto deployment for wu2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/wu2-AutoDeployTrigger-49365fcf-b58f-430d-afe3-fb718db6e2b6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WU2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WU2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WU2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: torosentdev.azurecr.io
          registryUsername: ${{ secrets.WU2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WU2_REGISTRY_PASSWORD }}
          containerAppName: wu2
          resourceGroup: preview-RG
          imageToBuild: torosentdev.azurecr.io/wu2:${{ github.sha }}
          dockerfilePath: Dockerfile


